export const SECTION_DATA = {
    "Company Overview": [
        { dataKey: "COMPANY_NAME", header: "Company Name" },
        { dataKey: "MI_KEY", header: "MI Key" },
        { dataKey: "CIK_NUMBER", header: "CIK Number" },
        { dataKey: "ADDRESS", header: "Address" },
        { dataKey: "COUNTRY_CODE", header: "Country/Region Code" },
        { dataKey: "GLOBAL_SUBREGION", header: "Global Subregion" },
        { dataKey: "GLOBAL_REGION", header: "Global Region" },
        { dataKey: "CITY_STATE", header: "City, State" },
        { dataKey: "LOCATION", header: "Location" },
        { dataKey: "POSTAL_CODE", header: "Postal Code" },
        { dataKey: "US_REGION", header: "U.S. Region" },
        { dataKey: "STATE_OF_INCORPORATION", header: "State of Incorporation" },
        { dataKey: "COUNTRY_OF_INCORPORATION", header: "Country of Incorporation" },
        { dataKey: "PHONE", header: "Phone Number" },
    ],
    "Financial Information": [
        { dataKey: "COMPANY_NAME", header: "Company Name" },
        { dataKey: "MARKET_CAPITALIZATION___M___1", header: "Market Capitalization ($M)" },
        { dataKey: "TOTAL_REVENUE__LATEST_FISCAL_YEAR____000__1", header: "Total Revenue [Latest Fiscal Year]" },
        { dataKey: "EBITDA__LATEST_FISCAL_YEAR____000__1", header: "EBITDA [Latest Fiscal Year]" },
        { dataKey: "EBIT__LATEST_FISCAL_YEAR____000__1", header: "EBIT [Latest Fiscal Year]" },
        { dataKey: "INTEREST_EXPENSE__LATEST_FISCAL_YEAR____000__1", header: "Interest Expense [Latest Fiscal Year]" },
        { dataKey: "NET_INCOME__LATEST_FISCAL_YEAR____000__1", header: "Net Income [Latest Fiscal Year]" },
        { dataKey: "CASH_AND_CASH_EQUIVALENTS__LATEST_FISCAL_YEAR____000__1", header: "Cash and Cash Equivalents [Latest Fiscal Year]" },
        { dataKey: "PROPERTY__PLANT_AND_EQUIPMENT__LATEST_FISCAL_YEAR____000__1", header: "Property, Plant and Equipment [Latest Fiscal Year]" },
        { dataKey: "TOTAL_ASSETS__LATEST_FISCAL_YEAR____000__1", header: "Total Assets [Latest Fiscal Year]" },
        { dataKey: "TOTAL_DEBT__LATEST_FISCAL_YEAR____000__1", header: "Total Debt [Latest Fiscal Year]" },
        { dataKey: "TOTAL_EQUITY__LATEST_FISCAL_YEAR____000__1", header: "Total Equity [Latest Fiscal Year]" },
        { dataKey: "COMMON_DIVIDENDS_DECLARED_PER_SHARE__LATEST_FISCAL_YEAR______1", header: "Common Dividends Declared per Share [Latest Fiscal Year] ($)" },
        { dataKey: "TEV__EBITDA__X__1", header: "TEV/ EBITDA (x)" },
        { dataKey: "PRICE__EPS_AFTER_EXTRA__X__1", header: "Price/ EPS After Extra (x)" },
        { dataKey: "PRICE__BOOK__X__1", header: "Price/ Book (x)" },
        { dataKey: "TOTAL_DEBT__TOTAL_EQUITY__LATEST_FISCAL_YEAR___X__1", header: "Total Debt/ Total Equity [Latest Fiscal Year] (x)" },
        { dataKey: "ROAA__LATEST_FISCAL_YEAR______1", header: "ROAA [Latest Fiscal Year] (%)" },
        { dataKey: "ROAE__LATEST_FISCAL_YEAR______1", header: "ROAE [Latest Fiscal Year] (%)" },
        { dataKey: "REPORTED_CURRENCY_CODE__LATEST_FISCAL_YEAR__1", header: "Reported Currency Code [Latest Fiscal Year]" },
        { dataKey: "PERIOD_ENDED__LATEST_FISCAL_YEAR___MM_DD_YYYY__1", header: "Period Ended [Latest Fiscal Year] (mm/dd/yyyy)" },
        { dataKey: "CASH___SHORT_TERM_INVESTMENTS__LATEST_FISCAL_YEAR____000__2", header: "Cash & Short Term Investments [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_ENTERPRISE_VALUE__CIQ____M__2", header: "Total Enterprise Value (CIQ) ($M)" },
        { dataKey: "NET_PROPERTY__PLANT___EQUIPMENT__LATEST_FISCAL_YEAR____000__2", header: "Net Property, Plant & Equipment [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_ASSETS__LATEST_FISCAL_YEAR____000__2", header: "Total Assets [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_DEBT__LATEST_FISCAL_YEAR____000__2", header: "Net Debt [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_DEBT__LATEST_FISCAL_YEAR____000__2", header: "Total Debt [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_PREFERRED_EQUITY__LATEST_FISCAL_YEAR____000__2", header: "Total Preferred Equity [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_COMMON_EQUITY__LATEST_FISCAL_YEAR____000__2", header: "Total Common Equity [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_MINORITY_INTEREST__LATEST_FISCAL_YEAR____000__2", header: "Total Minority Interest [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_REVENUE__LATEST_FISCAL_YEAR____000__2", header: "Total Revenue [Latest Fiscal Year] ($000)" },
        { dataKey: "GROSS_PROFIT__LATEST_FISCAL_YEAR____000__2", header: "Gross Profit [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_INCOME__LATEST_FISCAL_YEAR____000__2", header: "Net Income [Latest Fiscal Year] ($000)" },
        { dataKey: "EBIT__LATEST_FISCAL_YEAR____000__2", header: "EBIT [Latest Fiscal Year] ($000)" },
        { dataKey: "EBITDA__LATEST_FISCAL_YEAR____000__2", header: "EBITDA [Latest Fiscal Year] ($000)" },
        { dataKey: "CAPITAL_EXPENDITURE__LATEST_FISCAL_YEAR____000__2", header: "Capital Expenditure [Latest Fiscal Year] ($000)" },
        { dataKey: "CASH_FROM_INVESTING__LATEST_FISCAL_YEAR____000__2", header: "Cash from Investing [Latest Fiscal Year] ($000)" },
        { dataKey: "CASH_FROM_FINANCING__LATEST_FISCAL_YEAR____000__2", header: "Cash from Financing [Latest Fiscal Year] ($000)" },
        { dataKey: "CHANGE_IN_NET_WORKING_CAPITAL__LATEST_FISCAL_YEAR____000__2", header: "Change in Net Working Capital [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_DEBT_EQUITY__LATEST_FISCAL_YEAR______2", header: "Total Debt/Equity [Latest Fiscal Year] (%)" },
        { dataKey: "TOTAL_DEBT___EBITDA__LATEST_FISCAL_YEAR___X__2", header: "Total Debt / EBITDA [Latest Fiscal Year] (x)" },
        { dataKey: "TOTAL_REVENUES__1_YEAR_GROWTH__LATEST_FISCAL_YEAR______2", header: "Total Revenues, 1 Year Growth [Latest Fiscal Year] (%)" },
        { dataKey: "PAYOUT_RATIO__LATEST_FISCAL_YEAR______2", header: "Payout Ratio [Latest Fiscal Year] (%)" },
        { dataKey: "RETURN_ON_ASSETS__LATEST_FISCAL_YEAR______2", header: "Return on Assets [Latest Fiscal Year] (%)" },
        { dataKey: "RETURN_ON_EQUITY__LATEST_FISCAL_YEAR______2", header: "Return on Equity [Latest Fiscal Year] (%)" },
        { dataKey: "EBIT___INTEREST_EXPENSE__LATEST_FISCAL_YEAR___X__2", header: "EBIT / Interest Expense [Latest Fiscal Year] (x)" },
        { dataKey: "BOOK_VALUE_PER_SHARE__LATEST_FISCAL_YEAR______2", header: "Book Value per Share [Latest Fiscal Year] ($)" },
        { dataKey: "DIVIDENDS_PER_SHARE__LATEST_FISCAL_YEAR______2", header: "Dividends per Share [Latest Fiscal Year] ($)" },
        { dataKey: "BASIC_EPS__LATEST_FISCAL_YEAR______2", header: "Basic EPS [Latest Fiscal Year] ($)" },
        { dataKey: "DILUTED_EPS_EXCL__EXTRA_ITEMS__LATEST_FISCAL_YEAR______2", header: "Diluted EPS Excl. Extra Items [Latest Fiscal Year] ($)" },
        { dataKey: "WEIGHTED_AVG__BASIC_SHARES_OUT___LATEST_FISCAL_YEAR___ACTUAL__2", header: "Weighted Avg. Basic Shares Out. [Latest Fiscal Year] (actual)" },
        { dataKey: "WEIGHTED_AVG__DILUTED_SHARES_OUT___LATEST_FISCAL_YEAR___ACTUAL__2", header: "Weighted Avg. Diluted Shares Out. [Latest Fiscal Year] (actual)" },
        { dataKey: "CASH___SHORT_TERM_INVESTMENTS__LATEST_FISCAL_YEAR____000__3", header: "Cash & Short Term Investments [Latest Fiscal Year] ($000)" },
        { dataKey: "INVENTORY__LATEST_FISCAL_YEAR____000__3", header: "Inventory [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_CURRENT_ASSETS__LATEST_FISCAL_YEAR____000__3", header: "Total Current Assets [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_PROPERTY__PLANT___EQUIPMENT__LATEST_FISCAL_YEAR____000__3", header: "Net Property, Plant & Equipment [Latest Fiscal Year] ($000)" },
        { dataKey: "GOODWILL__LATEST_FISCAL_YEAR____000__3", header: "Goodwill [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_ASSETS__LATEST_FISCAL_YEAR____000__3", header: "Total Assets [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_CURRENT_LIABILITIES__LATEST_FISCAL_YEAR____000__3", header: "Total Current Liabilities [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_DEBT__LATEST_FISCAL_YEAR____000__3", header: "Total Debt [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_DEBT__LATEST_FISCAL_YEAR____000__3", header: "Net Debt [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_MINORITY_INTEREST__LATEST_FISCAL_YEAR____000__3", header: "Total Minority Interest [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_LIABILITIES__LATEST_FISCAL_YEAR____000__3", header: "Total Liabilities [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_PREFERRED_EQUITY__LATEST_FISCAL_YEAR____000__3", header: "Total Preferred Equity [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_COMMON_EQUITY__LATEST_FISCAL_YEAR____000__3", header: "Total Common Equity [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_EQUITY__LATEST_FISCAL_YEAR____000__3", header: "Total Equity [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_WORTH_-__REPORTED___LATEST_FISCAL_YEAR____000__3", header: "Net Worth - (Reported) [Latest Fiscal Year] ($000)" },
        { dataKey: "CAPITAL_EXPENDITURE_-__REPORTED___LATEST_FISCAL_YEAR____000__3", header: "Capital Expenditure - (Reported) [Latest Fiscal Year] ($000)" },
        { dataKey: "GROSS_PROFIT__LATEST_FISCAL_YEAR____000__3", header: "Gross Profit [Latest Fiscal Year] ($000)" },
        { dataKey: "OPERATING_INCOME__LATEST_FISCAL_YEAR____000__3", header: "Operating Income [Latest Fiscal Year] ($000)" },
        { dataKey: "NET_INCOME__LATEST_FISCAL_YEAR____000__3", header: "Net Income [Latest Fiscal Year] ($000)" },
        { dataKey: "EBITDA__LATEST_FISCAL_YEAR____000__3", header: "EBITDA [Latest Fiscal Year] ($000)" },
        { dataKey: "EBIT__LATEST_FISCAL_YEAR____000__3", header: "EBIT [Latest Fiscal Year] ($000)" },
        { dataKey: "TOTAL_ASSET_TURNOVER__LATEST_FISCAL_YEAR___X__3", header: "Total Asset Turnover [Latest Fiscal Year] (x)" },
        { dataKey: "EBIT___INTEREST_EXPENSE__LATEST_FISCAL_YEAR___X__3", header: "EBIT / Interest Expense [Latest Fiscal Year] (x)" },
        { dataKey: "RETURN_ON_ASSETS__LATEST_FISCAL_YEAR______3", header: "Return on Assets [Latest Fiscal Year] (%)" },
        { dataKey: "RETURN_ON_CAPITAL__LATEST_FISCAL_YEAR______3", header: "Return on Capital [Latest Fiscal Year] (%)" },
        { dataKey: "RETURN_ON_EQUITY__LATEST_FISCAL_YEAR______3", header: "Return on Equity [Latest Fiscal Year] (%)" },
        { dataKey: "TOTAL_REVENUE__LATEST_FISCAL_YEAR____000__3", header: "Total Revenue [Latest Fiscal Year] ($000)" },
    ],
    "Deals and Investors": [
        { dataKey: "INVESTOR_TYPE", header: "Investor Type" },
        { dataKey: "MERGER_TARGET_OR_MOE_PARTICIPANT_", header: "Merger Target or MOE Participant?" },
        { dataKey: "DIRECT_SUBSIDIARY_OF_MERGER_TARGET_", header: "Direct subsidiary of merger target?" },
        { dataKey: "MERGER_TARGET_DEAL_KEY", header: "Merger Target Deal Key" },
        { dataKey: "MERGER_TARGET_DEAL_STATUS", header: "Merger Target Deal Status" },
        { dataKey: "LATEST_ROUND_TYPE", header: "Latest Round Type" },
        { dataKey: "LATEST_ROUND_NUMBER", header: "Latest Round Number" },
        { dataKey: "LATEST_ROUND_OFFERING_SIZE", header: "Latest Round Offering Size" },
        { dataKey: "LATEST_ROUND_OFFERING_SIZE_-_ESTIMATED_", header: "Latest Round Offering Size - Estimated?" },
        { dataKey: "PRE-MONEY_VALUATION", header: "Pre-Money Valuation" },
        { dataKey: "LATEST_AVAILABLE_PRE-MONEY_VALUATION_TRANSACTION_DATE", header: "Latest Available Pre-Money Valuation Transaction Date" },
        { dataKey: "PRE-MONEY_VALUATION_-_ESTIMATED_", header: "Pre-Money Valuation - Estimated?" },
        { dataKey: "POST-MONEY_VALUATION", header: "Post-Money Valuation" },
        { dataKey: "LATEST_AVAILABLE_POST-MONEY_VALUATION_TRANSACTION_DATE", header: "Latest Available Post-Money Valuation Transaction Date" },
        { dataKey: "POST-MONEY_VALUATION_-_ESTIMATED_", header: "Post-Money Valuation - Estimated?" },
        { dataKey: "TOTAL_AMOUNT_RAISED", header: "Total Amount Raised" },
        { dataKey: "SPAC_STATUS", header: "SPAC Status" },
        { dataKey: "SPAC_EXPIRATION_DATE", header: "SPAC Expiration Date" },
        { dataKey: "MONTHS_TO_SPAC_EXPIRATION", header: "Months to SPAC Expiration" },
        { dataKey: "POTENTIAL_TARGET_INDUSTRY__MI_", header: "Potential Target Industry (MI)" },
        { dataKey: "POTENTIAL_TARGET_INDUSTRY__CIQ_GICS_", header: "Potential Target Industry (CIQ/GICS)" },
        { dataKey: "TOTAL_INVESTMENTS", header: "Total Investments" },
        { dataKey: "AVERAGE_TENURE", header: "Average Tenure" },
    ],
    "Shareholder Ownership": [
        { dataKey: "COMPANY_NAME", header: "Company Name" },
        { dataKey: "INSTITUTIONAL_OWNER_NAME", header: "Institutional Owner Name" },
        { dataKey: "PERCENT_HELD_BY_INSTITUTIONAL_OWNER", header: "Percent Held by Institutional Owner" },
        { dataKey: "SHARES_HELD_BY_INSTITUTIONAL_OWNER", header: "Shares Held by Institutional Owner" },
        { dataKey: "MARKET_VALUE_OF_INSTITUTIONAL_HOLDER", header: "Market Value of Institutional Holder" },
        { dataKey: "CHANGE_IN_SHARES_OF_INSTITUTIONAL_HOLDER", header: "Change in Shares of Institutional Holder" },
        { dataKey: "PERCENT_CHANGE_IN_SHARES_OF_INSTITUTIONAL_HOLDER", header: "Percent Change in Shares of Institutional Holder" },
        { dataKey: "INSTITUTIONAL_DERIVATIVES", header: "Institutional Derivatives" },
        { dataKey: "INSTITUTIONAL_OWNER_DATE", header: "Institutional Owner Date" },
        { dataKey: "INSIDER_OWNER_NAME", header: "Insider Owner Name" },
        { dataKey: "PERCENT_HELD_BY_INSIDER_OWNER", header: "Percent Held by Insider Owner" },
        { dataKey: "SHARES_HELD_BY_INSIDER_OWNER", header: "Shares Held by Insider Owner" },
        { dataKey: "MARKET_VALUE_OF_INSIDER_HOLDER", header: "Market Value of Insider Holder" },
        { dataKey: "CHANGE_IN_SHARES_OF_INSIDER_HOLDER", header: "Change in Shares of Insider Holder" },
        { dataKey: "PERCENT_CHANGE_IN_SHARES_OF_INSIDER_HOLDER", header: "Percent Change in Shares of Insider Holder" },
        { dataKey: "INSIDER_DERIVATIVES", header: "Insider Derivatives" },
        { dataKey: "INSIDER_OWNER_DATE", header: "Insider Owner Date" },
        { dataKey: "HOLDER_NAME", header: "Holder Name" },
        { dataKey: "HOLDER_TYPE", header: "Holder Type" },
        { dataKey: "PERCENT_HELD_BY_HOLDER", header: "Percent Held by Holder" },
        { dataKey: "SHARES_HELD_BY_HOLDER", header: "Shares Held by Holder" },
        { dataKey: "MARKET_VALUE_OF_HOLDER", header: "Market Value of Holder" },
        { dataKey: "CHANGE_IN_SHARES_OF_HOLDER", header: "Change in Shares of Holder" },
        { dataKey: "PERCENT_CHANGE_IN_SHARES_OF_HOLDER", header: "Percent Change in Shares of Holder" },
        { dataKey: "HOLDER_DERIVATIVES", header: "Holder Derivatives" },
        { dataKey: "HOLDER_DATE", header: "Holder Date" },
        { dataKey: "FUND_NAME", header: "Fund Name" },
        { dataKey: "PERCENT_HELD_BY_FUND", header: "Percent Held by Fund" },
        { dataKey: "SHARES_HELD_BY_FUND", header: "Shares Held by Fund" },
        { dataKey: "MARKET_VALUE_OF_FUND", header: "Market Value of Fund" },
        { dataKey: "CHANGE_IN_SHARES_OF_FUND", header: "Change in Shares of Fund" },
        { dataKey: "PERCENT_CHANGE_IN_SHARES_OF_FUND", header: "Percent Change in Shares of Fund" },
        { dataKey: "FUND_DERIVATIVES", header: "Fund Derivatives" },
        { dataKey: "FUND_DATE", header: "Fund Date" },
    ],
    "Parent Company Overview": [
        { dataKey: "COMPANY_NAME", header: "Company Name" },
        { dataKey: "PARENT_COMPANY_NAME", header: "Parent Company Name" },
        { dataKey: "PARENT_PERCENT_OWNED", header: "Parent Percent Owned" },
        { dataKey: "PARENT_TICKER", header: "Parent Ticker" },
        { dataKey: "PARENT_EXCHANGE__TICKER", header: "Parent Exchange: Ticker" },
        { dataKey: "PARENT_INDUSTRY", header: "Parent Industry" },
        { dataKey: "PARENT_CITY", header: "Parent City" },
        { dataKey: "PARENT_COUNTRY_REGION", header: "Parent Country/Region" },
        { dataKey: "ULTIMATE_PARENT_COMPANY_NAME", header: "Ultimate Parent Company Name" },
        { dataKey: "ULTIMATE_PARENT_COMPANY_MI_KEY", header: "Ultimate Parent Company MI Key" },
        { dataKey: "ULTIMATE_PARENT_TICKER", header: "Ultimate Parent Ticker" },
        { dataKey: "ULTIMATE_PARENT_EXCHANGE__TICKER", header: "Ultimate Parent Exchange: Ticker" },
        { dataKey: "ULTIMATE_PARENT_CITY", header: "Ultimate Parent City" },
        { dataKey: "ULTIMATE_PARENT_COUNTRY___REGION", header: "Institution Key of Beneficial Owner" },
        { dataKey: "MANAGING_AGENT_KI", header: "Managing Agent KI" },
        { dataKey: "MANAGING_AGENT_NAME", header: "Managing Agent Name" },
        { dataKey: "MANAGING_AGENT_GROUP_KI", header: "Managing Agent Group KI" },
        { dataKey: "MANAGING_AGENT_GROUP_NAME", header: "Managing Agent Group Name" },
    ],
    "People and Compensation": [
        { dataKey: "COMPANY_NAME", header: "Company Name" },
        { dataKey: "PERSON_S_FULL_NAME", header: "Person's Full Name" },
        { dataKey: "TITLE", header: "Title" },
        { dataKey: "APPROXIMATE_AGE", header: "Approximate Age" },
        { dataKey: "GENDER", header: "Gender" },
        { dataKey: "PERSON_DESCRIPTION", header: "Person Description" },
        { dataKey: "YEAR_HIRED", header: "Year Hired" },
        { dataKey: "PHONE", header: "Phone" },
        { dataKey: "EMAIL", header: "Email" },
        { dataKey: "CURRENT_PROFESSIONAL_AFFILIATIONS", header: "Current Professional Affiliations" },
        { dataKey: "PRIOR_PROFESSIONAL_AFFILIATION", header: "Prior Professional Affiliations" },
        { dataKey: "CURRENT_BOARD_MEMBERSHIPS", header: "Current Board Memberships" },
        { dataKey: "PRIOR_BOARD_MEMBERSHIPS", header: "Prior Board Memberships" },
        { dataKey: "EDUCATION_DETAIL", header: "Education Details" },
        { dataKey: "COMPENSATION_DATA_AS_OF", header: "Compensation Data as of" },
        { dataKey: "REPORTED_CURRENCY_CODE", header: "Reported Currency Code" },
        { dataKey: "COMPENSATION_TITLE", header: "Compensation Title" },
        { dataKey: "SALARY", header: "Salary" },
        { dataKey: "BONUS", header: "Bonus" },
        { dataKey: "OTHER_ANNUAL_COMPENSATION", header: "Other Annual Compensation" },
        { dataKey: "ALL_OTHER_COMPENSATION", header: "All Other Compensation" },
        { dataKey: "NON_EQUITY_INCENTIVE_PLAN_COMPENSATION", header: "Non-Equity Incentive Plan Compensation" },
        { dataKey: "NON_EQUITY_ANNUAL_INCENTIVE_PLAN", header: "Non Equity Annual Incentive Plan" },
        { dataKey: "NON_EQUITY_LONG_TERM_INCENTIVE_PLAN", header: "Non Equity Long Term Incentive Plan" },
        { dataKey: "TOTAL_ANNUAL_CASH_COMPENSATION", header: "Total Annual Cash Compensation" },
        { dataKey: "RESTRICTED_STOCK_AWARDS", header: "Restricted Stock Awards" },
        { dataKey: "OPTION_AWARDS", header: "Option Awards" },
        { dataKey: "LONG_TERM_INCENTIVE_PLAN", header: "Long Term Incentive Plan" },
        { dataKey: "CHANGE_IN_PENSION_PLAN_NON-QUALIFIED_DEFERREO", header: "Change in Pension Plan/Non-Qualified Deferred Comp Earnings" },
        { dataKey: "TOTAL_ANNUAL_NON-CASH_COMPENSATION", header: "Total Annual Non-Cash Compensation" },
        { dataKey: "TOTAL_CALCULATED_COMPENSATION", header: "Total Calculated Compensation" },
        { dataKey: "AS_REPORTED_TOTAL_COMPENSATION", header: "As Reported Total Executive Compensation" },
        { dataKey: "TOTAL_COMPENSATION_RECEIVED_EARNED", header: "Total Compensation Received/Earned" },
        { dataKey: "ESTIMATED_PAYMENTS_-_TERMINATION_WITHOUT_CAUS", header: "Estimated Payments - Termination Without Cause" },
        { dataKey: "ESTIMATED_PAYMENTS_-_CHANGE_IN_CONTROL", header: "Estimated Payments - Change in Control" },
    ],
}

export const SECTION_DATA_OLD = {
    "Overview of Companies": [
        { header: "Company Legal Name", dataKey: "companyLegalName" },
        { header: "Company ID", dataKey: "companyID" },
        { header: "Business Description", dataKey: "businessDescription" },
        { header: "Website", dataKey: "website" },
        { header: "Year Founded", dataKey: "yearFounded" },
        { header: "Business Status", dataKey: "businessStatus" },
        { header: "Entity Type", dataKey: "entityType" },
    ],
    "Company Details": [
        { header: "Key Words", dataKey: "keyWords" },
        { header: "Number of Employees", dataKey: "numberOfEmployees" },
        { header: "Key Contact Title", dataKey: "keyContactTitle" },
        { header: "Key Contact Email", dataKey: "keyContactEmail" },
        { header: "Key Contact Phone", dataKey: "keyContactPhone" },
        { header: "Exchange", dataKey: "exchange" },
        { header: "Ticker", dataKey: "ticker" },
        { header: "SIC Codes", dataKey: "sicCodes" },
        { header: "LinkedIn URL", dataKey: "linkedInURL" },
        { header: "Last UCC Filing Data", dataKey: "lastUCCFilingData" },
        { header: "Business Life Cycle", dataKey: "businessLifeCycle" },
        { header: "Ownership Status", dataKey: "ownershipStatus" },
    ],
    "Financial Metrics": [
        { header: "Revenue", dataKey: "revenue" },
        { header: "EBITDA", dataKey: "ebitda" },
        { header: "Financing Status", dataKey: "financingStatus" },
        { header: "Enterprise Value", dataKey: "enterpriseValue" },
        { header: "Total Raised", dataKey: "totalRaised" },
        { header: "Fiscal Period", dataKey: "fiscalPeriod" },
        { header: "Last Known Valuation", dataKey: "lastKnownValuation" },
    ],
    "Industries and Locations": [
        { header: "Primary Industry Sector", dataKey: "primaryIndustrySector" },
        { header: "Primary Industry Group", dataKey: "primaryIndustryGroup" },
        { header: "Primary Industry Code", dataKey: "primaryIndustryCode" },
        { header: "HQ Location", dataKey: "hqLocation" },
        { header: "HQ Global Sub Region", dataKey: "hqGlobalSubRegion" },
        { header: "HQ Global Region", dataKey: "hqGlobalRegion" },
    ],
    "Intellectual Property": [
        { header: "Total Patent Documents", dataKey: "totalPatentDocuments" },
        { header: "Total Patent Families", dataKey: "totalPatentFamilies" },
        { header: "Active Patent Documents", dataKey: "activePatentDocuments" },
        { header: "Pending Patent Documents", dataKey: "pendingPatentDocuments" },
        { header: "Patents Expiring Next Year", dataKey: "patentsExpiringNextYear" },
        { header: "Top CPC Codes", dataKey: "topCPCCodes" },
    ]
}

export const TABLE_ROW_ITEM = {
    companyLegalName: "Stripe",
    companyID: "12345",
    businessDescription: "Investor Platform",
    website: "Stripe.com",
    yearFounded: 2000,
    businessStatus: "Active",
    entityType: "LLC",
    keyWords: "software, development, cloud",
    numberOfEmployees: 50,
    keyContactTitle: "CEO",
    keyContactEmail: "info@example.com",
    keyContactPhone: "123-456-7890",
    exchange: "NYSE",
    ticker: "EXMP",
    sicCodes: "7371",
    linkedInURL: "linkedin.com/company/example",
    lastUCCFilingData: "2023-10-26",
    businessLifeCycle: "Growth",
    ownershipStatus: "Private",
    revenue: "$1.2M",
    ebitda: "$500K",
    financingStatus: "Series A",
    enterpriseValue: "$10M",
    totalRaised: "$2M",
    fiscalPeriod: "2023",
    lastKnownValuation: "$8M",
    primaryIndustrySector: "Information Technology",
    primaryIndustryGroup: "Software",
    primaryIndustryCode: "7371",
    hqLocation: "New York",
    hqGlobalSubRegion: "North America",
    hqGlobalRegion: "Americas",
    totalPatentDocuments: 10,
    totalPatentFamilies: 5,
    activePatentDocuments: 8,
    pendingPatentDocuments: 2,
    patentsExpiringNextYear: 0,
    topCPCCodes: "G06F 17/00",
}